spring.application.name=teto-backend

# Conexão com o Banco de Dados
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:teto_db}
spring.datasource.username=${DB_USER:teto_user}
spring.datasource.password=${DB_PASSWORD:teto_password}

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true