spring.application.name=teto-backend

# ConexÃ£o com o Banco de Dados
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:teto_db}
spring.datasource.username=${DB_USER:teto_user}
spring.datasource.password=${DB_PASSWORD:teto_password}

# ConfiguraÃ§Ãµes do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Configurações de Segurança
api.security.token.issuer=${JWT_ISSUER:teto-app}
api.security.token.secret=${JWT_SECRET:chave_secreta_super_segura_para_desenvolvimento_local}
api.security.token.hourslifetime=${JWT_HOURS_LIFETIME:2}
